### PR TITLE
Write tests

### PR DESCRIPTION
**Pull request by nathanbegbie**

### CODE REVIEW

**Comment by nathanbegbie** [comment]
@smn pls review

**Comment by smn** [comment]
Looks good but looking at Travis it doesn't look like it's finding the tests it needs to run?

**Comment by smn** [comment]
:+1:

**Comment by smn** [comment]
oops! Missed a bit, `create` and `announce` test methods weren't prefixed with `test_` and so they're not recognised as tests. Renamed those and now one is failing :/ Sorry, have some :cake:

**Pull request merged**
